CFG = {
    'data_dir': 'data',
    'csv_dir': 'csv',
    'plot_dir': 'plots',
    'log_dir': 'logs',
    'out_dir': 'outputs',
    'img_size': 96,
    'val_split': 0.3,
    'seed': 42,
    'epochs': 5,
    'batch_size': 64,
    'lr': 1e-3,
    'weight_decay': 1e-4,
    'num_workers': 4,
    'pin_memory': True,
    'amp': True,
    'models': ['cnn', 'alexnet', 'resnet50', 'vgg16'],
    'task1_model': 'cnn_mlp',
    'task2_transform': 'lda',
    'task3_transform': 'reglda',
    'mlp_hidden_dim': 256,
    'mlp_dropout': 0.35,
    'projector_max_samples': 32768,
    'lda_solver': 'svd',
    'lda_shrinkage': 'auto',
    'run_eda': False,
}
